main: su.nightexpress.excellentenchants.EnchantsPlugin
version: '${project.version}'
name: ExcellentEnchants
author: NightExpress
desciption: Amazing enchantments with seamless integration.
depend: [ nightcore ]
softdepend: [ ProtocolLib, PlaceholderAPI, MythicMobs, mcMMO ]
api-version: 1.20
load: STARTUP